title: Ali Anıl Koçak
description: "Ali Anıl Koçak Kişisel Blog"
author:
  name: "AliAnilKocak"
  email: "alianilkocak@gmail.com"
  url: "https://alianilkocak.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "alianilkocak"
year : "2021"
